name: MERN CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install backend dependencies
      working-directory: ./server
      run: npm install

    - name: Run backend tests
      working-directory: ./server
      env:
        MONGODB_URI: mongodb://localhost:27017/jobboard_test
        JWT_SECRET: test_secret_key
        NODE_ENV: test
      run: npm test || echo "No backend tests yet"

    - name: Install frontend dependencies
      working-directory: ./client
      run: npm install

    - name: Build frontend
      working-directory: ./client
      env:
        CI: false
        REACT_APP_API_URL: http://localhost:5000
      run: npm run build || echo "Build not ready"
