name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    # Root project setup
    - name: Install root dependencies
      run: |
        npm install
      continue-on-error: true
      
    # Client setup and tests
    - name: Install client dependencies
      working-directory: ./client
      run: |
        npm install
        
    - name: Build client
      working-directory: ./client
      run: |
        CI=false npm run build
      
    - name: Test client
      working-directory: ./client
      run: |
        CI=true npm test -- --passWithNoTests --watchAll=false
      
    # Server setup and tests
    - name: Install server dependencies
      working-directory: ./server
      run: |
        npm install
      
    - name: Test server
      working-directory: ./server
      run: |
        npm test

    # Optional linting (won't fail the build)
    - name: Run linting
      run: |
        npm run lint || true
      continue-on-error: true 